pod 'AFNetworking', '3.1.0'
pod 'MBProgressHUD', '0.9.2'
pod 'Masonry'
pod 'IQKeyboardManager', '3.3.7'
#pod 'YYCategories'
pod 'MJExtension'
pod 'SDCycleScrollView'
pod 'SDAutoLayout'
pod 'SDWebImage'